### ISSUE TITLE
Improve plugin UX

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#260]
```[tasklist]
### Tasks
- [x] Improve messages shown to user
- [x] If using non-docked EIS Wizard, show messages in the plugin window
- [ ] Clarify which parameters are optional (and other parameter improvements)
- [x] Fix (interpolation box) and improve proxy processing views
- [x] Add confirmation dialog to EIS Toolkit upgrading in Settings
- [x] Add tooltips (proxy processing)
- [x] Add output log to proxy processing views
- [x] Add user manual link to Wizard About
- [x] Convert exceptions to messages
```
