### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#45]
```[tasklist]
### Tasks
- [ ] Update description about the plan
- [ ] Update architecture diagram
- [ ] Add testing instructions and requirements
- [ ] Update or remove development docs
```
