### ISSUE TITLE
Add processing algorithms for random forest, gradient boosting and logistic regression

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#47]
```[tasklist]
### Tasks
- [ ] Logistic regression
- [ ] Random forest classifier
- [ ] Random forest regressor
- [ ] Gradient boosting classifier
- [ ] Gradient boosting regressor
```
