### ISSUE TITLE
Implement functionality to modeling wizard ML methods

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_qgis_plugin#93]
```[tasklist]
### Tasks
- [x] Random forest classifier training
- [x] Random forest regressor training
- [x] Gradient boosting classifier training
- [x] Gradient boosting regressor training
- [x] Logistic regression training
- [x] Evaluate model
- [x] Predict
```
